[features]
seeds = false
skip-lint = false
[programs.devnet]
r08_anchor_mintnft = "Ev6qyFGDh4eiYgEiN1Pcp6dMQ2Zzme5vJcibaogCvwdG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
